### ISSUE TITLE
If primaryCategory is unsure, it could be because there is no consensus. Ppl who chose stuff other than unsure should not be treated as getting it wrong. Need to think of a way to deal with this.

### ISSUE THREAD

**Issue by madanalogy** [bettersg/checkMate#224]
We could consider removing messages assessed as unsure from the accuracy calculation altogether

**Comment by sarge1989** [comment]
See comment in #225, accuracy aside, there's also a need to manage the frontend state in the message display. Where the checker has diverged from the final assessed vote, i.e. "wrong" state, they need to see it visually so they go in and review it.
