### ISSUE TITLE
Move message to voted tab once I have voted not once message is assessed. Probably need to handle this frontend since voted status only changes asynchronously backend.

### ISSUE THREAD

**Issue by madanalogy** [bettersg/checkMate#225]
> Move message to voted tab once I have voted not once message is assessed.

I vaguely recall we had a discussion about this. Just to confirm, is the intention to only have two tabs (voted / not voted)? So then differentiating between assessed / not assessed is done in a different manner / not at all? Since there are 2 state variables each message can be in 1 of 4 states, so making explicit which tab / colour /font it should be in for each state would be good.

> Probably need to handle this frontend since voted status only changes asynchronously backend.

We can set a react hook to fetch messages after voting. Alternatively we can include the updated message state in the api response. The latter might be more data efficient but might require more changes to existing interfaces.

**Comment by sarge1989** [comment]
@madanalogy Also, to be pedantic, theres still one more set of variables, "correct" and "wrong", assuming the checker has voted on the message and it is also assessed. This also relates to #224
