### ISSUE TITLE
Move onboarding from Telegram bot to Telegram webapp

### ISSUE THREAD

**Issue by madanalogy** [bettersg/checkMate#226]
We might need to do this anyway if we go down the singpass verification route. This could be linked to https://github.com/bettersg/checkMate/issues/223 as well, since if we go down the otp route it might be better managed on the webapp too.

We will need to consider messaging though, since when checkers first hit `/start` we can only send them a message (I think we can't open up the web app). There's also now an additional confirmation dialog they would have to get through to access the webapp (see screenshot) which could deter onboarding

![image](https://github.com/bettersg/checkMate/assets/42177597/f7f686ed-83b5-40b6-89f3-2e8e981bb295)

**Comment by sarge1989** [comment]
I suppose the confirmation dialog is inevitable if we're going the tg webapp route? Anyway, I think it's okay cos the checkers can be expected to have higher commitment/will. As for the /start, maybe we can prompt them to click the dashboard button or provide a link in the response. @TY0018 any thoughts?

**Comment by TY0018** [comment]
Maybe the intro msg when they click start can provide them the link to the privacy policy(?) or sth to give them more assurance so that when the confirmation dialog pops up, they wont be as deterred to enter.

Yep, the msg can prompt them to click the dashboard button to begin onboarding on the web app

**Comment by madanalogy** [comment]
Alright let's move to having the onboarding happen on the web app then. Would be easier to build in the otp flow too I'm guessing

**Comment by btjl** [comment]
Hi I'll be actively working on this feature!
https://github.com/bettersg/checkMate/pull/238

**Comment by btjl** [comment]
Code has been implemented via https://github.com/bettersg/checkMate/pull/252

UAT testing in progress.
