### ISSUE TITLE
Refactor user handler to isolate whatsapp-specific logic from rest of checking mechanism

### ISSUE THREAD

**Issue by sarge1989** [bettersg/checkMate#278]
## Context/Rationale
- Eventually, we might want to expand sources of new instances/messages beyond whatsapp, e.g. telegram or even API.
- Currently, the newTextInstanceHandler and newImageInstanceHandler are coupled together with whatsapp-specific logic, but with slight changes these two functions can probably be hived off.

## Remarks
- both functions newTextInstanceHandler and newImageInstanceHandler should be refactored out into its own newInstanceHandler
   - newImageInstanceHandler should accept a generic download URL and token as parameters, rather than "mediaId" which is whatsapp specific
- newInstance handler should be platform agnostic. Perhaps it should be pub/sub triggered, with a new instance object being created in the queue (https://firebase.google.com/docs/functions/pubsub-events?gen=2nd)
- remaining whatsapp-specific logic could be shifted back into the webhook handler for whatsapp?

**Comment by sarge1989** [comment]
@btjl when you are free and done with the website tasks, can work on this I guess! It's not super urgent and will give you a good platform to properly get familiar with the most core parts of the codebase.

**Comment by btjl** [comment]
Having looked through the code, I think not just the handlers but the instance object itself has many WhatsApp-specific properties. Curious if you'd like to keep it this way, so something like a parent instance class representing properties that are platform agnostic, followed by extending the class to platform-specific properties?

**Comment by sarge1989** [comment]
Yeah @btjl I agree! We can do something like the above. Can feel free to propose how a new data object can look like for instances. Originally it was built just for whatsapp, but I think it's worth thinking about how to make it agnostic
