### ISSUE TITLE
Checkers App Vote Page Back Button

### ISSUE THREAD

**Issue by sarge1989** [bettersg/checkMate#284]
- Currently there's no way to go back to the previous page when on the individual vote page
- We would ideally want the user to go back to the page he came from, i.e. the search results page
    - Added complication is that if the user clicked in search results page 5, he should go back there. which is not the native behavior right now as he will be taken back to the starting page if the app just navigates back to /votes

**Comment by sarge1989** [comment]
@btjl can help with this?

**Comment by btjl** [comment]
Okay I can look into this
